[package]
name = "cosmic-bwarden-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmic-bwarden-core = { path = "../cosmic-bwarden-core" }
anyhow = { workspace = true }
rsa = { workspace = true, features = ["sha2"] }
sha2 = { workspace = true }
sha1 = { workspace = true }
ssh-agent-lib = "0.5.1"
signature = "2.2"
rand = { workspace = true }
rand_core = "0.6"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "time", "io-util", "sync"] }
tokio-stream = { version = "0.1", features = ["net"] }
chrono = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = "0.11"
libc = "0.2"
rustix = { workspace = true }
zbus = { workspace = true }
futures-util = "0.3"
oo7 = { version = "0.3", optional = true }

[features]
default = []
keyring = ["dep:oo7"]
