[package]
name = "cosmic-bwarden-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmic-bwarden-core = { path = "../cosmic-bwarden-core" }
anyhow = "1.0"
rsa = { version = "0.9.9", features = ["sha2"] }
sha2 = "0.10"
sha1 = "0.10"
ssh-agent-lib = "0.5.1"
signature = "2.2"
rand = "0.8"
rand_core = "0.6"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
arboard = "3.6.1"
libc = "0.2"
rustix = { version = "0.38", features = ["process"] }
zbus = "4.4"
futures-util = "0.3"
oo7 = { version = "0.3", optional = true }

[features]
default = []
keyring = ["dep:oo7"]
