[package]
name = "cosmic-bwarden-tests"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
thirtyfour = { version = "0.31", optional = true }
zip = { version = "2.1", optional = true }
cosmic-bwarden-core = { path = "../cosmic-bwarden-core" }
testcontainers = { version = "0.23", features = ["http_wait"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
reqwest = { version = "0.12", features = ["json"] }
tempfile = "3.10"
postcard = { version = "1.0", features = ["alloc"] }
serde_json = "1.0"
walkdir = "2"
tokio-util = "0.7"
uuid = { version = "1.0", features = ["v4"] }

[features]
browser-e2e = ["thirtyfour", "zip"]
tpm-smoke = []

[lints]
workspace = true
