[package]
name = "cosmic-bwarden-cli"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
authors = ["Don Enikeev <donat@enikeev.net>"]

[dependencies]
cosmic-bwarden-core = { path = "../cosmic-bwarden-core" }
clap = { version = "4.5", features = ["derive", "env"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "io-util"] }
anyhow = { workspace = true }
rpassword = "7.3"

[lints]
workspace = true
